spring:
  datasource:
    url: jdbc:mysql://database-1.c7e8yu8mafox.ap-southeast-2.rds.amazonaws.com:3306/mydatabase
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    username: admin
#    password: thsdutks1004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect